"""
Emergency Alerts Service — Real-time Red-tier Escalation & Dispatch for ASHA & Admin.
Tracks critical triage alerts generated by the clinical state machine and field encounters.
"""
import json
import logging
from typing import List, Dict, Any, Optional
from datetime import datetime
from sqlalchemy import select, insert, update, and_, desc
from app.db import get_db_connection, emergency_alerts_table, row_to_dict, rows_to_dicts

logger = logging.getLogger("sanjeevani.alerts")


def record_emergency_alert(
    conversation_id: str,
    user_id: Optional[int] = None,
    patient_name: Optional[str] = None,
    village: Optional[str] = None,
    phone: Optional[str] = None,
    symptoms: Optional[str] = None,
    clinical_flags: Optional[List[str]] = None,
    tier: str = "Red",
) -> Optional[int]:
    """Records an unhandled Red-tier emergency alert into the database."""
    flags_str = json.dumps(clinical_flags or [])
    try:
        with get_db_connection() as conn:
            stmt = insert(emergency_alerts_table).values(
                conversation_id=conversation_id,
                user_id=user_id,
                patient_name=patient_name or "Anonymous Patient",
                village=village or "Unspecified Ward",
                phone=phone or "--",
                symptoms=symptoms or "Acute clinical distress",
                clinical_flags=flags_str,
                tier=tier,
                acknowledged=False,
                acknowledged_by=None,
            )
            res = conn.execute(stmt)
            inserted_id = res.inserted_primary_key[0] if res.inserted_primary_key else None
            logger.warning(
                f"[ALERT DISPATCH] Critical Red alert recorded: ID={inserted_id} conv={conversation_id} village={village}"
            )
            return inserted_id
    except Exception as e:
        logger.error(f"[ALERT ERROR] Failed to record emergency alert: {e}", exc_info=True)
        return None


def get_emergency_alerts(
    village: Optional[str] = None,
    only_unacknowledged: bool = False,
    limit: int = 50,
) -> List[Dict[str, Any]]:
    """Fetches emergency triage alerts for ASHA workers and Admins."""
    try:
        with get_db_connection() as conn:
            conditions = []
            if village and village.strip() and village.lower() != "all":
                conditions.append(emergency_alerts_table.c.village.ilike(f"%{village.strip()}%"))
            if only_unacknowledged:
                conditions.append(emergency_alerts_table.c.acknowledged == False)

            stmt = select(emergency_alerts_table)
            if conditions:
                stmt = stmt.where(and_(*conditions))
            stmt = stmt.order_by(desc(emergency_alerts_table.c.id)).limit(limit)

            rows = conn.execute(stmt).fetchall()
            alerts = []
            for r in rows_to_dicts(rows):
                if isinstance(r.get("clinical_flags"), str):
                    try:
                        r["clinical_flags"] = json.loads(r["clinical_flags"])
                    except Exception:
                        r["clinical_flags"] = [r["clinical_flags"]]
                if isinstance(r.get("created_at"), datetime):
                    r["created_at"] = r["created_at"].isoformat()
                alerts.append(r)
            return alerts
    except Exception as e:
        logger.error(f"[ALERT ERROR] Failed to fetch emergency alerts: {e}", exc_info=True)
        return []


def acknowledge_emergency_alert(alert_id: int, acknowledged_by: str) -> bool:
    """Marks an emergency alert as acknowledged/dispatched by ASHA worker or Admin."""
    try:
        with get_db_connection() as conn:
            stmt = (
                update(emergency_alerts_table)
                .where(emergency_alerts_table.c.id == alert_id)
                .values(
                    acknowledged=True,
                    acknowledged_by=acknowledged_by,
                )
            )
            res = conn.execute(stmt)
            return res.rowcount > 0
    except Exception as e:
        logger.error(f"[ALERT ERROR] Failed to acknowledge emergency alert {alert_id}: {e}", exc_info=True)
        return False
